Repository dirtyg2120/thesis-backend, pull requests merged in 2022-03, with the labels that each got.

#23 Show uvicorn access log
  app/main.py
Labels: bug

#21 Change anonymous user authentication flow
  app/api/report.py
  app/services/report.py
  app/services/scrape.py
  app/tests/test_report.py
  doc/sequence-diagrams/img/user_report.svg
  doc/sequence-diagrams/src/diagrams.md
Labels: enhancement, not finished

#28 Add logging handler to database
  app/main.py
  app/models/log_record.py
  app/services/log_db_handler.py
Labels: enhancement

#25 Refactor TwitterScraper class to follow single-responsibility principle
  app/api/auth.py
  app/api/scraper.py
  app/services/report.py
  app/services/scrape.py
  app/tests/test_auth.py
  app/tests/test_report.py
Labels: enhancement

#27 Add URL parser for scraper endpoint
  app/api/scraper.py
  app/services/url_parser.py
  app/tests/test_scraper.py
Labels: enhancement

#29 Testing Update
  app/services/report.py
  app/tests/conftest.py
  app/tests/data/user.json
  app/tests/helpers/__init__.py
  app/tests/helpers/auth_helpers.py
  app/tests/helpers/check_helpers.py
  app/tests/helpers/mock_models.py
  app/tests/helpers/report_helpers.py
  app/tests/scripts/get_user_data.py
  app/tests/test_auth.py
  app/tests/test_background_task.py
  app/tests/test_report.py
  app/tests/test_scraper.py
  conftest.py
Labels: enhancement, finish

#32 Save session in database
  app/api/report.py
  app/models/__init__.py
  app/models/session.py
Labels: enhancement

#37 Refactor tests
  .env.test
  .github/workflows/check.yaml
  app/core/config.py
  app/main.py
  app/tests/__init__.py
  app/tests/conftest.py
  app/tests/helpers/auth_helpers.py
  app/tests/helpers/check_helpers.py
  app/tests/helpers/report_helpers.py
  app/tests/test_auth.py
  app/tests/test_background_task.py
  app/tests/test_report.py
  app/tests/test_scraper.py
  conftest.py
  pyproject.toml
  requirements.txt
Labels: enhancement
