Repository dirtyg2120/thesis-backend, pull requests merged in 2022-05, with the labels that each got.

#40 Integrate with ML model
  .github/workflows/check.yaml
  app/api/scraper.py
  app/models/bot_prediction.py
  app/models/report.py
  app/schemas/__init__.py
  app/schemas/twitter.py
  app/services/bot_checker.py
  app/services/ml.py
  app/services/report.py
  app/services/scrape.py
  app/tests/conftest.py
  app/tests/test_background_task.py
  model/__init__.py
  model/gnn.py
  model/inference.py
  model/sobog.py
  model_data/__init__.py
  pyproject.toml
  requirements.txt
Labels: enhancement, do not merge

#49 Feature/export profile
  .gitignore
  app/api/report.py
  app/models/__init__.py
  app/models/report.py
  app/schemas/__init__.py
  app/schemas/report.py
  app/services/ml.py
  app/services/report.py
  app/services/scrape.py
  app/tests/conftest.py
  app/tests/data/__init__.py
  app/tests/data/tweets.json
  app/tests/data/user.json
  app/tests/helpers/mock_models.py
  app/tests/test_report.py
  app/tests/test_scraper.py
Labels: finished

#50 Show both waiting and approved reports
  app/api/report.py
  app/api/scraper.py
  app/models/bot_prediction.py
  app/models/report.py
  app/models/twitter.py
  app/schemas/report.py
  app/schemas/twitter.py
  app/services/bot_checker.py
  app/services/ml.py
  app/services/report.py
  app/tests/test_background_task.py
  app/tests/test_report.py
  pyproject.toml
Labels: enhancement

#51 VERY HOT FIX
  app/api/ml.py
  app/api/report.py
  app/api/scraper.py
  app/main.py
  app/models/bot_prediction.py
  app/models/report.py
  app/models/twitter.py
  app/schemas/report.py
  app/services/bot_checker.py
  app/services/ml.py
  app/services/report.py
  app/services/scrape.py
  app/services/url_parser.py
  app/tests/data/user.json
  app/tests/test_report.py
  app/tests/test_scraper.py
  app/utils.py
Labels: bug, help wanted, not finished
